const t=(key,label,o={})=>({key,label,type:'text',...o})
export const F={
  profile:[t('name','Nama'),t('headline','Headline'),t('hero_title','Judul Hero'),t('hero_subtitle','Subjudul Hero',{type:'textarea'}),t('avatar_url','Foto profil',{type:'image',folder:'profile'}),t('cv_url','CV (PDF)',{type:'file',folder:'cv',accept:'application/pdf'}),t('location','Lokasi')],
  about:[t('bio','Biografi',{type:'textarea',hint:'Pisahkan paragraf dengan satu baris kosong.'}),t('education_text','Pendidikan'),t('focus_text','Fokus'),t('stats','Statistik',{type:'stats',hint:'Satu per baris, format: Nilai | Label. Contoh: S1 | Manajemen'})],
  contact:[t('contact_title','Judul bagian kontak'),t('email','Email'),t('whatsapp','WhatsApp',{hint:'Format internasional tanpa +, contoh: 6281234567890'}),t('location','Lokasi')],
  experience:[t('role','Jabatan'),t('company','Perusahaan'),t('period','Periode',{hint:'Contoh: 2023 – Sekarang'}),t('bullets','Tanggung jawab',{type:'textarea',hint:'Satu poin per baris.'})],
  project:[t('title','Judul'),t('slug','Slug',{hint:'Kosongkan untuk dibuat otomatis dari judul.'}),t('category','Kategori'),t('description','Deskripsi',{type:'textarea'}),t('thumbnail_url','Thumbnail',{type:'image',folder:'projects'}),t('technologies','Teknologi',{hint:'Pisahkan dengan koma. Contoh: Apps Script, Google Sheets'}),t('project_url','Link proyek'),t('github_url','Link GitHub'),t('featured','Featured',{type:'check'})],
  certificate:[t('title','Nama sertifikat'),t('issuer','Penerbit / lembaga'),t('issued_at','Tahun atau tanggal terbit'),t('description','Deskripsi',{type:'textarea'}),t('image_url','Gambar sertifikat',{type:'image',folder:'certificates'}),t('credential_url','Link verifikasi (opsional)')],
  education:[t('institution','Institusi'),t('degree','Gelar'),t('field','Jurusan'),t('start_year','Tahun mulai'),t('end_year','Tahun selesai'),t('description','Deskripsi',{type:'textarea'}),t('logo_url','Logo',{type:'image',folder:'education'})],
  category:[t('name','Nama kategori')],
  skill:[t('name','Nama skill'),{key:'category_id',label:'Kategori',type:'select',table:'skill_categories',show:'name'}],
  social:[t('platform','Platform',{hint:'linkedin, github, atau instagram (untuk ikon yang sesuai)'}),t('url','URL')],
  settings:[t('site_title','Judul website'),t('meta_description','Deskripsi (SEO)',{type:'textarea'}),t('og_image_url','Gambar Open Graph',{type:'image',folder:'site'}),t('favicon_url','Favicon',{type:'image',folder:'site'}),t('logo_text','Teks logo / monogram'),t('footer_text','Teks footer'),t('accent_color','Warna aksen',{type:'color'}),t('bg_color','Warna latar halaman',{type:'color'}),t('card_color','Warna kartu',{type:'color'}),t('text_color','Warna teks',{type:'color'}),t('dark_color','Warna blok gelap (tombol, kartu statistik, bagian kontak)',{type:'color'}),t('nav_color','Warna bentuk menu (Home, About, dst.)',{type:'color'}),t('navtext_color','Warna teks menu',{type:'color'})]
,
  plan:[t('name','Nama paket',{hint:'Contoh: 3 Bulan, 1 Tahun, Lifetime'}),t('code','Kode unik',{hint:'Huruf kecil tanpa spasi, contoh: 3-bulan. Dipakai di link pembelian.'}),t('description','Deskripsi singkat',{type:'textarea'}),{key:'duration_months',label:'Lama aktif (bulan)',type:'number',hint:'KOSONGKAN untuk paket Lifetime. Contoh: 3 = 3 bulan, 12 = 1 tahun.'},{key:'price',label:'Harga (Rp)',type:'number',hint:'Harga yang dibayar pelanggan. Minimal 1000. Contoh: 249000'},{key:'original_price',label:'Harga coret (Rp, opsional)',type:'number',hint:'Harga sebelum diskon. Kosongkan jika tidak ada.'},t('features','Daftar fitur',{type:'textarea',hint:'Satu fitur per baris.'}),{key:'is_popular',label:'Tandai sebagai paling populer',type:'check',def:false},{key:'active',label:'Aktif (tampil & bisa dibeli)',type:'check',def:true}],
  app:[t('brand_name','Nama brand / produk'),t('tagline','Tagline (judul tab browser)'),t('hero_title','Judul utama landing page'),t('hero_subtitle','Subjudul landing page',{type:'textarea'}),t('support_whatsapp','WhatsApp bantuan',{hint:'Format internasional tanpa +, contoh: 6281234567890'}),t('support_email','Email bantuan'),t('sample_username','Username portofolio nyata untuk contoh',{hint:'Opsional. Isi username pengguna yang sudah ada untuk menampilkan tombol "Lihat portofolio nyata".'}),t('verify_time','Perkiraan waktu verifikasi pembayaran',{hint:'Contoh: maksimal 1x24 jam'}),t('announcement','Pengumuman di atas landing page',{hint:'Opsional. Contoh: Diskon 30% sampai akhir bulan!'})],
  paymethod:[{key:'type',label:'Jenis',type:'choice',options:[['qris','QRIS'],['ewallet','E-Wallet'],['bank','Transfer Bank']]},t('label','Nama',{hint:'Contoh: QRIS, GoPay, DANA, BCA, BRI, Mandiri'}),t('account_name','Atas nama',{hint:'Nama pemilik rekening / akun'}),t('account_number','Nomor rekening / nomor e-wallet',{hint:'Kosongkan untuk QRIS'}),{key:'image_url',label:'Gambar QRIS (opsional untuk e-wallet/bank)',type:'image',folder:'payments'},t('instructions','Petunjuk pembayaran',{type:'textarea',hint:'Tampil di halaman pembayaran pelanggan.'}),{key:'active',label:'Aktif (tampil ke pelanggan)',type:'check',def:true}]
}
